spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cyxdev?ServerTimezone=Asia/Shanghai
    username: root
    password: 010911
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.itemmanagement.mapper
